version: "3.6"

services:
  database:
    image: "websublime/postgres"
    container_name: "database"
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ${DATA_PATH}/database:/var/lib/postgresql/data
      - ${PWD}/database:/docker-entrypoint-initdb.d/

  minio:
    image: "minio/minio"
    container_name: "minio"
    ports:
      - ${MINIO_PORT}:9000
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      #- MINIO_ROOT_USER=${MINIO_ROOT_USER}
      #- MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH}/minio:/data
